---

- name: install dependent packages to build php
  yum: name={{ item }}
  with_items:
    - re2c
    - libxml2-devel
    - bison-devel
    - openssl-devel
    - curl-devel
    - libjpeg-devel
    - libpng-devel
    - libmcrypt-devel
    - readline-devel
    - libtidy-devel
    - libxslt-devel
    - httpd-devel
    - enchant-devel
    - libXpm-devel
    - freetype-devel
    - t1lib-devel
    - gmp-devel
    - libc-client-devel
    - libicu-devel
    - oniguruma-devel
    - net-snmp-devel
    - bzip2-devel

- name: install php
  command: >
    {{ xbuild_install_dir_prefix }}/xbuild/php-install {{ xbuild_php_version }}
    {{ xbuild_install_dir_prefix }}/php-{{ xbuild_php_version }}
    creates={{ xbuild_install_dir_prefix }}/php-{{ xbuild_php_version }}

- name: update php.ini
  template: >
    src=php.ini.j2
    dest={{ xbuild_install_dir_prefix}}/php-{{ xbuild_php_version }}/etc/php.ini
    owner=root
    group=root
    mode=0644
