---

- name: install dependent packages to build python
  yum: name={{ item }} state=present
  with_items:
    - expat-devel
    - libGL-devel
    - tcl-devel
    - tk-devel
    - libX11-devel
    - glibc-devel
    - tix-devel
    - bzip2-devel
    - sqlite-devel
    - db4-devel
    - libffi-devel
    - valgrind-devel
    - systemtap-sdt-devel

- name: install python
  command: >
    {{ xbuild_install_dir_prefix }}/xbuild/python-install {{ xbuild_python_version }}
    {{ xbuild_install_dir_prefix }}/python-{{ xbuild_python_version }}
    creates={{ xbuild_install_dir_prefix }}/python-{{ xbuild_python_version }}

